import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-center py-24'>
        <h1 className="font-extrabold text-4xl py-10">
          tiny.nosaka.dev
        </h1>

        <p>
          Paste your URL
        </p>

      </main>
    </div>
  )
}

export default Home